### ISSUE TITLE
Dev branch will not build for sagecal_gpu, not on DAS5/fs5 headnode, nor on other node

### ISSUE THREAD

**Issue by HannoSpreeuw** [nlesc-dirac/sagecal#99]
`make` gives

> Scanning dependencies of target oslmfit
[  1%] Building C object src/lib/Dirac/CMakeFiles/oslmfit.dir/oslmfit.c.o
[  2%] Linking CXX shared library ../../../dist/lib/liboslmfit.so
../../../../src/lib/Dirac/oslmfit.o: In function `oslevmar_der_single_cuda':
/home/hspreeuw/sagecal-code/src/lib/Dirac/oslmfit.c:99: multiple definition of `oslevmar_der_single_cuda'
CMakeFiles/oslmfit.dir/oslmfit.c.o:oslmfit.c:(.text+0x0): first defined here
/usr/bin/ld: ../../../../src/lib/Dirac/oslmfit.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [dist/lib/liboslmfit.so] Error 1
make[1]: *** [src/lib/Dirac/CMakeFiles/oslmfit.dir/all] Error 2
make: *** [all] Error 2

1. ssh to fs5 headnode or other node
2. cd sagecal 
3. git checkout dev && git pull
4. mkdir build
5. cd build
6.  module load cmake/3.8.2 mpich/ge/gcc/64/3.2 gcc/4.9.3 casacore/2.3.0-gcc-4.9.3 wcslib/5.16-gcc-4.9.3 cfitsio/3.410-gcc-4.9.3 blas/gcc/64/3.7.0 openblas/0.2.20 cuda91/toolkit/9.1.85
7. cmake .. -DCMAKE_INSTALL_PREFIX=/some/install/dir -DHAVE_CUDA=ON
8. make

**Expected behavior**
Complete build

**Comment by HannoSpreeuw** [comment]
So it doesn't build with [gcc 4.9.3 set of packages](https://github.com/nlesc-dirac/sagecal/blob/dev/scripts/load_das5_astron_modules_gcc4.sh).
I will try [the gcc 6.3.0 set of packages](https://github.com/nlesc-dirac/sagecal/blob/dev/scripts/load_das5_astron_modules_gcc6.sh) first. See if that builds.

**Comment by HannoSpreeuw** [comment]
Nope.  The gcc 6.3.0 set of packages on the headnode gives the same error.

**Comment by HannoSpreeuw** [comment]
I'll be browsing through the last couple of commits to sort this out.

**Comment by HannoSpreeuw** [comment]
Might be commit 687f06b5b838b3525fefd93bbd6dda561b0427bb or commit e67b7cb859987e427b5d48cf837459baac02b918

> compile libraries befor binary

**Comment by HannoSpreeuw** [comment]
`export CFLAGS="-fPIC"`
before the cmake command didn't fix it.

**Comment by HannoSpreeuw** [comment]
`cmake .. -DCMAKE_INSTALL_PREFIX=/some/install/dir`,
so no CUDA support, does lead to a complete build. At least, on the headnode.

**Comment by HannoSpreeuw** [comment]
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)` in `CMakeLists.txt`
nor
`set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -g -O3 -fPIC")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g -pg -fPIC -W....`
make a difference.

**Comment by HannoSpreeuw** [comment]
I don't understand the error message, since I don't see multiple definitions of `oslevmar_der_single_cuda`. 
It seems only defined once, in `lib/Dirac/oslmfit.c`, line 61.

**Comment by SarodYatawatta** [comment]
I have seen something like this before, I will have a look

**Comment by HannoSpreeuw** [comment]
I tried building `sagecal_gpu` by reverting to previous commits.
Can't build `sagecal_gpu` from the `dev` branch (with the cmake command from above) back to and including commit 749def7ec99d953a72664f2bbbe65cee7aef8607.
But the build from that commit and some of its immediate successors fails for a different reason.

**Comment by HannoSpreeuw** [comment]
The supposed multiple definition of `oslevmar_der_single_cuda` probably comes from too many #includes.

**Comment by SarodYatawatta** [comment]
It works for me, did you clean your build dir before running cmake?

**Comment by SarodYatawatta** [comment]
see /home/syatawat/sagecal/build

**Comment by HannoSpreeuw** [comment]
Yes, I used a clean build dir.
Which modules did you load?
Was this on the fs5 headnode?

**Comment by SarodYatawatta** [comment]
Yes, I followed your commands exactly

**Comment by SarodYatawatta** [comment]
[syatawat@fs5 sagecal]$ git status
# On branch dev
nothing to commit, working directory clean
[syatawat@fs5 sagecal]$ module load cmake/3.8.2 mpich/ge/gcc/64/3.2 gcc/4.9.3 casacore/2.3.0-gcc-4.9.3 wcslib/5.16-gcc-4.9.3 cfitsio/3.410-gcc-4.9.3 blas/gcc/64/3.7.0 openblas/0.2.20 cuda91/toolkit/9.1.85
[syatawat@fs5 sagecal]$ rm -rf build/*
[syatawat@fs5 sagecal]$ cd build
[syatawat@fs5 build]$ cmake .. -DHAVE_CUDA=ON
works for me

**Comment by HannoSpreeuw** [comment]
I can confirm a successful build with a clean clone of sagecal.
I can also confirm my original results, with a clean build directory.

> [hspreeuw@fs5 sagecal-code]$ rm -rf build
[hspreeuw@fs5 sagecal-code]$ mkdir build
[hspreeuw@fs5 sagecal-code]$ cd build
[hspreeuw@fs5 build]$ cmake .. -DCMAKE_INSTALL_PREFIX=../install -DHAVE_CUDA=ON


So this still does not make sense.
`git status` only mentions untracked files.

> [hspreeuw@fs5 build]$ git pull
Already up-to-date.

**Comment by SarodYatawatta** [comment]
'confirm my original results' : can you be specific: does it build or not build?

**Comment by HannoSpreeuw** [comment]
@SarodYatawatta it does not build ( with the `multiple definition of ...` error).

Apparently cleaning the build directory is not sufficient. Not clear to me if any products from previous build attempts are still floating around in some other directory.
Anyway, `make clean` does not fix it.

**Comment by SarodYatawatta** [comment]
So 
rm -rf build 
does solve it?

**Comment by HannoSpreeuw** [comment]
No, it does not.
The only way (for me) is a fresh `git clone`.

**Comment by SarodYatawatta** [comment]
Ok, probably something to do with your env.
Lets make a note of this and close this issue.

**Comment by HannoSpreeuw** [comment]
That doesn't work for me. I can't do a fresh 'git clone` every time.

**Comment by SarodYatawatta** [comment]
No, but you can start with a clean shell.

**Comment by HannoSpreeuw** [comment]
Well, I hope you understood that that didn't suffice.

**Comment by HannoSpreeuw** [comment]
Thanks for your env. 
Copying your PATH and LD_LIBRARY_PATH did not make a difference.

**Comment by HannoSpreeuw** [comment]
So the problem was old object files floating around.

> [hspreeuw@fs5 build]$ l ../src/lib/Dirac/*.o
-rw-rw-r-- 1 hspreeuw hspreeuw  98368 Aug 17  2017 ../src/lib/Dirac/admm_solve.o
-rw-rw-r-- 1 hspreeuw hspreeuw  27488 Aug 17  2017 ../src/lib/Dirac/consensus_poly.o
-rw-rw-r-- 1 hspreeuw hspreeuw  98624 Aug 17  2017 ../src/lib/Dirac/rtr_solve_robust_cuda.o
-rw-rw-r-- 1 hspreeuw hspreeuw 158968 Aug 17  2017 ../src/lib/Dirac/robust_fl.o
-rw-rw-r-- 1 hspreeuw hspreeuw  68824 Aug 17  2017 ../src/lib/Dirac/clmfit_fl.o
-rw-rw-r-- 1 hspreeuw hspreeuw 170608 Aug 17  2017 ../src/lib/Dirac/robustlm.o
-rw-rw-r-- 1 hspreeuw hspreeuw  11416 Aug 17  2017 ../src/lib/Dirac/barrier.o
-rw-rw-r-- 1 hspreeuw hspreeuw 163480 Aug 17  2017 ../src/lib/Dirac/residual.o
-rw-rw-r-- 1 hspreeuw hspreeuw  98088 Aug 17  2017 ../src/lib/Dirac/clmfit.o
-rw-rw-r-- 1 hspreeuw hspreeuw  56216 Aug 17  2017 ../src/lib/Dirac/myblas.o
-rw-rw-r-- 1 hspreeuw hspreeuw 144216 Aug 17  2017 ../src/lib/Dirac/lmfit.o
-rw-rw-r-- 1 hspreeuw hspreeuw  18488 Aug 17  2017 ../src/lib/Dirac/load_balance.o
-rw-rw-r-- 1 hspreeuw hspreeuw 108496 Aug 17  2017 ../src/lib/Dirac/rtr_solve_robust_cuda_admm.o
-rw-rw-r-- 1 hspreeuw hspreeuw  73544 Aug 17  2017 ../src/lib/Dirac/diag_fl.o
-rw-rw-r-- 1 hspreeuw hspreeuw  87104 Aug 17  2017 ../src/lib/Dirac/rtr_solve_cuda.o
-rw-rw-r-- 1 hspreeuw hspreeuw  67840 Aug 17  2017 ../src/lib/Dirac/robust_lbfgs_nocuda.o
-rw-rw-r-- 1 hspreeuw hspreeuw  78056 Aug 17  2017 ../src/lib/Dirac/mderiv_fl.o
-rw-rw-r-- 1 hspreeuw hspreeuw 165168 Aug 17  2017 ../src/lib/Dirac/rtr_solve_robust_admm.o
-rw-rw-r-- 1 hspreeuw hspreeuw  51344 Aug 17  2017 ../src/lib/Dirac/manifold_average.o
-rw-rw-r-- 1 hspreeuw hspreeuw  49648 Aug 17  2017 ../src/lib/Dirac/diagnostics.o
-rw-rw-r-- 1 hspreeuw hspreeuw 540464 Aug 17  2017 ../src/lib/Dirac/manifold_fl.o
-rw-rw-r-- 1 hspreeuw hspreeuw  38008 Aug 17  2017 ../src/lib/Dirac/updatenu.o
-rw-rw-r-- 1 hspreeuw hspreeuw  44944 Aug 17  2017 ../src/lib/Dirac/oslmfit.o
-rw-rw-r-- 1 hspreeuw hspreeuw 205192 Aug 17  2017 ../src/lib/Dirac/robust.o
-rw-rw-r-- 1 hspreeuw hspreeuw  90448 Aug 17  2017 ../src/lib/Dirac/clmfit_nocuda.o
-rw-rw-r-- 1 hspreeuw hspreeuw 350832 Aug 17  2017 ../src/lib/Dirac/mderiv.o
-rw-rw-r-- 1 hspreeuw hspreeuw  80832 Aug 17  2017 ../src/lib/Dirac/lbfgs.o
[hspreeuw@fs5 build]$ l ../src/lib/Radio/*.o
-rw-rw-r-- 1 hspreeuw hspreeuw 2697000 Aug 17  2017 ../src/lib/Radio/predict_model.o
-rw-rw-r-- 1 hspreeuw hspreeuw  826992 Aug 17  2017 ../src/lib/Radio/predict_model_device.o
-rw-rw-r-- 1 hspreeuw hspreeuw  148416 Aug 17  2017 ../src/lib/Radio/predict_withbeam_gpu.o
-rw-rw-r-- 1 hspreeuw hspreeuw  111064 Aug 17  2017 ../src/lib/Radio/predict_withbeam.o
-rw-rw-r-- 1 hspreeuw hspreeuw   14544 Aug 17  2017 ../src/lib/Radio/stationbeam.o
-rw-rw-r-- 1 hspreeuw hspreeuw   30208 Aug 17  2017 ../src/lib/Radio/transforms.o
-rw-rw-r-- 1 hspreeuw hspreeuw  143536 Aug 17  2017 ../src/lib/Radio/predict.o
-rw-rw-r-- 1 hspreeuw hspreeuw   59856 Aug 17  2017 ../src/lib/Radio/readsky.o
[hspreeuw@fs5 build]$ rm ../src/lib/Dirac/*.o
[hspreeuw@fs5 build]$ rm ../src/lib/Radio/*.o

sagecal now builds successfully.
